POST http://localhost:3001/chat/stream
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXRuMHN6Nm0wMDAwajBvOHVreTE2N3p0IiwiZW1haWwiOiJ0ZXN0M0B5b3BtYWlsLmNvbSIsImlhdCI6MTc4ODg3NTQxMiwiZXhwIjoxNzg4ODc2MzEyfQ.CiytDgUcASwiCH9-R6nmggc8CLDJSHkGlqjb4DOkMnE
Content-Type: application/json

{
    "question": "What technologies do i know?",
    "sessionId": "cmtspoyox0001j0k8ja9wigdy"
}